apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: knative-routing-demo
  namespace: default
spec:
  revisionTemplate:
    spec:
      container:
        image: docker.io/gswk/knative-routing-demo:latest
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "1"
